/*
 * This file is generated by jOOQ.
 */
package today.ihelio.jooq;


import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import today.ihelio.jooq.tables.Categories;
import today.ihelio.jooq.tables.Hashtags;
import today.ihelio.jooq.tables.Todo;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefaultSchema extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>DEFAULT_SCHEMA</code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

    /**
     * The table <code>categories</code>.
     */
    public final Categories CATEGORIES = Categories.CATEGORIES;

    /**
     * The table <code>hashtags</code>.
     */
    public final Hashtags HASHTAGS = Hashtags.HASHTAGS;

    /**
     * The table <code>todo</code>.
     */
    public final Todo TODO = Todo.TODO;

    /**
     * No further instances allowed
     */
    private DefaultSchema() {
        super("", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Categories.CATEGORIES,
            Hashtags.HASHTAGS,
            Todo.TODO
        );
    }
}
