/*
 * This file is generated by jOOQ.
 */
package today.ihelio.jooq;


import today.ihelio.jooq.tables.Categories;
import today.ihelio.jooq.tables.Hashtags;
import today.ihelio.jooq.tables.Todo;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>categories</code>.
     */
    public static final Categories CATEGORIES = Categories.CATEGORIES;

    /**
     * The table <code>hashtags</code>.
     */
    public static final Hashtags HASHTAGS = Hashtags.HASHTAGS;

    /**
     * The table <code>todo</code>.
     */
    public static final Todo TODO = Todo.TODO;
}
