/*
 * This file is generated by jOOQ.
 */
package today.ihelio.jooq.tables;


import java.time.LocalDateTime;
import java.util.function.Function;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Function7;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Records;
import org.jooq.Row7;
import org.jooq.Schema;
import org.jooq.SelectField;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import today.ihelio.jooq.DefaultSchema;
import today.ihelio.jooq.Keys;
import today.ihelio.jooq.tables.records.TodoRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Todo extends TableImpl<TodoRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>todo</code>
     */
    public static final Todo TODO = new Todo();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TodoRecord> getRecordType() {
        return TodoRecord.class;
    }

    /**
     * The column <code>todo.id</code>.
     */
    public final TableField<TodoRecord, String> ID = createField(DSL.name("id"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>todo.content</code>.
     */
    public final TableField<TodoRecord, String> CONTENT = createField(DSL.name("content"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>todo.is_done</code>.
     */
    public final TableField<TodoRecord, Integer> IS_DONE = createField(DSL.name("is_done"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>todo.category</code>.
     */
    public final TableField<TodoRecord, String> CATEGORY = createField(DSL.name("category"), SQLDataType.VARCHAR(64), this, "");

    /**
     * The column <code>todo.hashtags</code>.
     */
    public final TableField<TodoRecord, String> HASHTAGS = createField(DSL.name("hashtags"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>todo.created_at</code>.
     */
    public final TableField<TodoRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(0), this, "");

    /**
     * The column <code>todo.is_deleted</code>.
     */
    public final TableField<TodoRecord, Integer> IS_DELETED = createField(DSL.name("is_deleted"), SQLDataType.INTEGER, this, "");

    private Todo(Name alias, Table<TodoRecord> aliased) {
        this(alias, aliased, null);
    }

    private Todo(Name alias, Table<TodoRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>todo</code> table reference
     */
    public Todo(String alias) {
        this(DSL.name(alias), TODO);
    }

    /**
     * Create an aliased <code>todo</code> table reference
     */
    public Todo(Name alias) {
        this(alias, TODO);
    }

    /**
     * Create a <code>todo</code> table reference
     */
    public Todo() {
        this(DSL.name("todo"), null);
    }

    public <O extends Record> Todo(Table<O> child, ForeignKey<O, TodoRecord> key) {
        super(child, key, TODO);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public UniqueKey<TodoRecord> getPrimaryKey() {
        return Keys.TODO__PK_TODO;
    }

    @Override
    public Todo as(String alias) {
        return new Todo(DSL.name(alias), this);
    }

    @Override
    public Todo as(Name alias) {
        return new Todo(alias, this);
    }

    @Override
    public Todo as(Table<?> alias) {
        return new Todo(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Todo rename(String name) {
        return new Todo(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Todo rename(Name name) {
        return new Todo(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Todo rename(Table<?> name) {
        return new Todo(name.getQualifiedName(), null);
    }

    // -------------------------------------------------------------------------
    // Row7 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row7<String, String, Integer, String, String, LocalDateTime, Integer> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Function)}.
     */
    public <U> SelectField<U> mapping(Function7<? super String, ? super String, ? super Integer, ? super String, ? super String, ? super LocalDateTime, ? super Integer, ? extends U> from) {
        return convertFrom(Records.mapping(from));
    }

    /**
     * Convenience mapping calling {@link SelectField#convertFrom(Class,
     * Function)}.
     */
    public <U> SelectField<U> mapping(Class<U> toType, Function7<? super String, ? super String, ? super Integer, ? super String, ? super String, ? super LocalDateTime, ? super Integer, ? extends U> from) {
        return convertFrom(toType, Records.mapping(from));
    }
}
